/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IRiCodeLine: typeof import('~icons/ri/code-line')['default']
    IRiExternalLinkLine: typeof import('~icons/ri/external-link-line')['default']
    IRiFileCopyLine: typeof import('~icons/ri/file-copy-line')['default']
    IRiFlaskLine: typeof import('~icons/ri/flask-line')['default']
    IRiGithubLine: typeof import('~icons/ri/github-line')['default']
  }
}
